title: James Laubach # your name (or website title) here
logo: "/images/IMG_0289[2].JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Graduate of the University of Tennessee at Martin
  <br><br>
  BS Computer Science 
  <br><br>
  <a href="www.linkedin.com/in/jamclaub/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
